<?php

namespace Dorvidas\Ratings\Tests\Models;

use Dorvidas\Ratings\Models\Rating;
use Dorvidas\Ratings\Tests\TestCase;

class RatingTest extends TestCase
{
    protected $user;
    protected $post;
    protected $book;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->loadLaravelMigrations(['--database' => 'testing']);

        $this->artisan('migrate', ['--database' => 'testing']);

        (new \Dorvidas\Ratings\Tests\Migrations\CreatePostsTable)->up();
        (new \Dorvidas\Ratings\Tests\Migrations\CreateBooksTable)->up();

        $this->withFactories(__DIR__ . '/../factories');

        $this->user = factory(\Dorvidas\Ratings\Tests\Models\User::class)->create();

        $this->post = factory(\Dorvidas\Ratings\Tests\Models\Post::class)->create();

        $this->book = factory(\Dorvidas\Ratings\Tests\Models\Book::class)->create();

        $this->actingAs($this->user);

    }

    /** @test */
    public function it_can_rating_via_for_model_scope()
    {
        $this->post->rate()->give(5);
        $this->post->rate()->give(3);
        $this->book->rate()->give(1);
        Rating::of($this->post);
        $this->assertCount(2, Rating::of($this->post)->get());
    }
}